ordering_manage/odering_manage/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ordering_info/', include('ordering_info.urls'))
]

ordering_manage/ordering_info/urls.py
# ordering_info urls

from django.urls import path
from ordering_info.views import *

app_name = 'ordering_info'
urlpatterns = [
    path('', list_orderings, name='list orderings'),
    path('<int:order_id>/show_details/', show_detail, name='show detail'),
    path('<int:order_id>/modify-info/', modify_order, name='modify info'),
    path('<int:order_id>/delete/', delete_order, name="delete order"),
    path('search_orders/', search_orders, name='search orders'),
    path('<int:user_id>/user-info/', show_userinfo, name='show userinfo'),
    path('search_userinfo/', search_userinfo, name='search userinfo'),
    path('adduser/', add_user, name='add user'),
]

ordering_manage/ordering_info/models.py
from django.db import models
from django import forms

# Create your models here.


class ShopInfo(models.Model):
    # shop info

    SHOP_TYPE_CHOICES = (
        (0, 'known'),
        (1, 'taobao'),
        (2, 'tmall')
    )
    shopId = models.CharField(max_length=40)
    shopName = models.CharField(max_length=80)
    phoneNumber = models.CharField(max_length=16)   # 0 - null
    shopType = models.SmallIntegerField(choices=SHOP_TYPE_CHOICES)           # 0 - null; 1 - taobao; 2 - Tmall

    def get_shop_type(self):
        shop_types = ['known', 'taobao', 'tmall']
        return shop_types[self.shopType]
    get_shop_type.short_description = 'ShopType'


class ShopOrder(models.Model):
    # shop order
    dateTime = models.DateField()
    shopId = models.ForeignKey(ShopInfo, on_delete=models.CASCADE)
    itemLink = models.URLField()
    itemName = models.CharField(max_length=64)
    itemCode = models.CharField(max_length=12)
    remark = models.TextField()
    requirements = models.TextField()

    def get_shop_name(self):
        return self.shopId.shopName
    get_shop_name.short_description = 'ShopName'


class UserInfo(models.Model):
    userTaobaoId = models.CharField(max_length=64, null=True)
    wxName = models.CharField(max_length=64, null=True)
    recommendWxName = models.CharField(max_length=64, null=True)
    wxGroupName = models.CharField(max_length=64, null=True)
    remark = models.TextField(null=True)


class OrderDetail(models.Model):
    # order details
    # 已完成、未完成、未返款、已返款
    FINISH_STATUS_CHOICES = (
        (-1, '异常'),
        (0, '未完成'),
        (1, '已完成')
    )

    RETURN_MONEY_CHOICES = (
        (-1, '异常'),
        (0, '未返款'),
        (1, '已返款')
    )

    TALK_CHOICES = (
        (0, '否'),
        (1, '是')
    )

    EXCEPTION_CHOICES = (
        (0, '错误'),
        (1, '正确')
    )
    dateTime = models.DateField()
    itemCode = models.ForeignKey(ShopOrder, on_delete=models.CASCADE)
    keywords = models.CharField(max_length=64)      # max length of keywords is 60 bytes
    enterChannel = models.CharField(max_length=24)
    scanDuration = models.SmallIntegerField()       # time of scan shopping items
    # whether need to talk with custome service staff or not
    talk = models.SmallIntegerField(choices=TALK_CHOICES)
    shoppingCnt = models.SmallIntegerField()        # number of purchased items
    # item should be purchased orderCnt times that could be searched by the keywords
    orderCnt = models.SmallIntegerField()
    price = models.FloatField()                     # price of item
    charges = models.FloatField()                   # our salary
    memo = models.TextField()                       # customers' memos
    salary = models.FloatField()                    # employees' salary each order
    # status of order: -1 - exception, 0 - unfinished, 1 - finished.
    # the order is  finished only after payed by customers
    finishStatus = models.SmallIntegerField(choices=FINISH_STATUS_CHOICES)
    # 0 - not return, 1 - had returned, -1 - exception
    moneyReturnStatus = models.SmallIntegerField(choices=RETURN_MONEY_CHOICES)
    # description of exceptions. If one order occured an exception, finishedStatus and moneyReturnStatus should be -1
    exception = models.SmallIntegerField(choices=EXCEPTION_CHOICES)
    remark = models.TextField()
    userTaobaoId = models.ForeignKey(UserInfo, on_delete=models.CASCADE)

    def get_shop_name(self):
        return self.itemCode.shopId.shopName
    get_shop_name.short_description = 'ShopName'

    def get_item_name(self):
        return self.itemCode.itemName
    get_item_name.short_description = 'ItemName'


class OrderInfoForm(forms.ModelForm):
    class Meta:
        model = OrderDetail
        # itemCode is foreign key, in form it can not modify directly, so fields doesn't contain itemCode.
        # but itemCode should be processed when modify order info
        fields = ('dateTime', 'keywords', 'enterChannel', 'scanDuration', 'talk', 'shoppingCnt',
                  'orderCnt', 'price', 'charges', 'memo', 'salary', 'finishStatus', 'moneyReturnStatus',
                  'exception', 'remark', 'userTaobaoId')

ordering_manage/ordering_info/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.template import RequestContext
from django.http import HttpResponseRedirect
from ordering_info.models import OrderDetail, OrderInfoForm, UserInfo

# Create your views here.


def list_orderings(request):
    order_details_lists = OrderDetail.objects.all().order_by('dateTime')
    paginator = Paginator(order_details_lists, 20)
    page = request.GET.get('page')
    order_details = paginator.get_page(page)

    return render(request, 'ordering_info/index.html', {'order_posts': order_details}, RequestContext(request))


def show_detail(request, order_id):
    order_detail = OrderDetail.objects.get(id=order_id)
    if order_detail.price <= 100:
        order_detail.salary = 6
    elif (order_detail.price > 100) and (order_detail.price <= 200):
        order_detail.salary = 7
    else:
        order_detail.salary = 8
    order_detail.save()
    return render(request, 'ordering_info/order-detail.html', {'order_detail': order_detail}, RequestContext(request))


def modify_order(request, order_id):
    order_detail = OrderDetail.objects.get(id=order_id)
    if request.method == 'POST':
        form = OrderInfoForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            order_detail.dateTime = post.dateTime
            order_detail.keywords = post.keywords
            order_detail.enterChannel = post.enterChannel
            order_detail.scanDuration = post.scanDuration
            order_detail.talk = post.talk
            order_detail.shoppingCnt = post.shoppingCnt
            order_detail.orderCnt = post.orderCnt
            order_detail.price = post.price
            order_detail.charges = post.charges
            order_detail.memo = post.memo
            order_detail.salary = post.salary
            order_detail.finishStatus = post.finishStatus
            print('finishStatus:' + post.finishStatus)
            order_detail.moneyReturnStatus = post.moneyReturnStatus
            order_detail.exception = post.exception
            order_detail.remark = post.remark
            order_detail.userTaobaoId = post.userTaobaoId
            order_detail.save()

    return HttpResponseRedirect('/ordering_info/')


def delete_order(request, order_id):
    OrderDetail.objects.filter(id=order_id).delete()
    return HttpResponseRedirect('/ordering_info/')


def search_orders(request):
    datetime = request.GET.get('datetime')
    keywords = request.GET.get('keywords')
    finish_status = request.GET.get('finishStatus')
    money_return_status = request.GET.get('moneyReturnStatus')
    user_taobao_id = request.GET.get('userTaobaoId')

    # filter
    results = OrderDetail.objects.filter(finishStatus=finish_status)\
        .filter(moneyReturnStatus=money_return_status).order_by('dateTime')
    if datetime:
        results = results.filter(dateTime=datetime)
    if keywords:
        results = results.filter(keywords__contains=keywords)
    if user_taobao_id:
        results = results.filter(userTaobaoId__userTaobaoId__contains=user_taobao_id)

    paginator = Paginator(results, 20)
    page = request.GET.get('page')
    order_posts = paginator.get_page(page)

    return render(request, 'ordering_info/index.html', {'order_posts': order_posts}, RequestContext(request))


def show_userinfo(request, user_id):
    err_msg = ''
    user_info = UserInfo.objects.filter(id__exact=user_id)
    if not user_info.exists():
        err_msg = '当前搜索用户不存在，请确保搜索输入正确或添加新用户信息'

    return render(request, 'ordering_info/user-info.html', {'user_info': user_info, 'err_msg': err_msg},
                  RequestContext(request))


def search_userinfo(request):
    user_taobao_name = request.GET.get('userTaobaoId')
    user_wxname = request.GET.get('wxName')
    user_recommend_wxname = request.GET.get('recommendWxName')
    user_wx_group_name = request.GET.get('wxGroupName')
    err_msg = ''
    user_info = UserInfo.objects.all()

    if user_taobao_name or user_wxname or user_recommend_wxname or user_wx_group_name:
        if user_taobao_name:
            user_info = user_info.filter(userTaobaoId__contains=user_taobao_name)
        if user_wxname:
            user_info = user_info.filter(wxName__contains=user_wxname)
        if user_recommend_wxname:
            user_info = user_info.filter(recommendWxName__contains=user_recommend_wxname)
        if user_wx_group_name:
            user_info = user_info.filter(wxGroupName__contains=user_wx_group_name)

    if not user_info.exists():
        err_msg = '当前搜索用户不存在，请确保搜索输入正确或添加新用户信息'

    paginator = Paginator(user_info, 20)
    page = request.GET.get('page')
    user_infos = paginator.get_page(page)
    return render(request, 'ordering_info/user-info.html', {'user_info': user_infos, 'err_msg': err_msg},
                  RequestContext(request))


def add_user(request):
    if request.method == 'POST':
        new_user = UserInfo(
            userTaobaoId=request.POST.get('newUserTaobaoId'),
            wxName=request.POST.get('newWxName'),
            recommendWxName=request.POST.get('newRecommendWxName'),
            wxGroupName=request.POST.get('newWxGroupName'),
            remark=request.POST.get('newRemark')
        )

        if new_user.userTaobaoId:
            new_user.save()

    return HttpResponseRedirect('/ordering_info/search_userinfo/')

ordering_manage/ordering_info/templates/ordering_info/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>订单列表</title>

    {% include 'ordering_info/search-base.html' %}
    <br>

    <table border="1" cellspacing="0" style="border:none;line-height:29px;height:29px;border-radius:1px;width:100%;">
        <tr>
            <!-- 时间、店铺名称、商品名称、购买件数、价格、淘宝用户名、是否完成、是否返款、异常、操作 -->
            <td align="center">序号</td>
            <td align="center">时间</td>
            <td align="center">店铺名称</td>
            <td align="center">商品名称</td>
            <td align="center">购买件数</td>
            <td align="center">价格</td>
            <td align="center">淘宝用户名</td>
            <td align="center">是否完成</td>
            <td align="center">是否返款</td>
            <td align="center">订单是否出错</td>
            <td align="center">操作</td>
        </tr>
        {% for order_post in order_posts %}
        <tr>
            <td align="center">{{ forloop.counter }}</td>
            <td align="center">{{order_post.dateTime | date:'Y-n-d'}}</td>
            <td align="center">{{order_post.itemCode.shopId.shopName}}</td>
            <td align="center">{{order_post.itemCode.itemName}}</td>
            <td align="center">{{order_post.orderCnt}}</td>
            <td align="center">{{order_post.price }} 元</td>
            <td align="center">
                <a style="text-decoration:none" href="{% url 'ordering_info:show userinfo' order_post.userTaobaoId.id %}">{{order_post.userTaobaoId.userTaobaoId}}</a>
            </td>
            <td align="center">{{order_post.get_finishStatus_display}}</td>
            <td align="center">{{order_post.get_moneyReturnStatus_display}}</td>
            <td align="center">{{order_post.get_exception_display}}</td>
            <td align="center">
                <!-- 详细信息、删除、修改 -->
                <button type="submit" name="detail" class="btn btn-orderinfo">
                    <a href="{% url 'ordering_info:show detail' order_post.id %}" style="text-decoration:none;">详细信息</a>
                </button>
                <button type="submit" name="delete" class="btn btn-orderinfo">
                    <a href="{% url 'ordering_info:delete order' order_post.id %}" style="text-decoration:none;">删除</a>
                </button>
            </td>
        </tr>
        {% endfor %}
    </table>

    <div style="margin-top:5px;" class="pagination">
        <span class="step-links">
            {% if order_posts.has_previous %}
            <a style="text-decoration:none" href="?page=1">&laquo; first</a>
            <a style="text-decoration:none" href="?page={{ order_posts.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ order_posts.number }} of {{ order_posts.paginator.num_pages }}
            </span>

            {% if order_posts.has_next %}
            <a href="?page={{ order_posts.next_page_number }}">next</a>
            <a href="?page={{ order_posts.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</head>
<body>

</body>
</html>

ordering_manage/ordering_info/templates/ordering_info/order-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>订单详情</title>

    <div>
        <h2>店铺信息</h2>
        <!-- 店铺ID、店铺名称、联系方式、店铺类型 -->
        <ul>
            <li>     店铺ID: {{order_detail.itemCode.shopId.shopId}}</li>
            <li>   店铺名称: {{order_detail.itemCode.shopId.shopName}}</li>
            <li>联系方式: {{order_detail.itemCode.shopId.phoneNumber}}</li>
            <li>   店铺类型: {{order_detail.itemCode.shopId.get_shopType_display}}</li>
        </ul>
    </div>
    <div>
        <!-- 商品信息 时间、商品名称、商品编码、商品链接、备注、要求 -->
        <h2>商品信息</h2>
        <ul>
            <li>      时间: {{order_detail.itemCode.dateTime | date:'Y-n-d'}}</li>
            <li>   商品名称: {{order_detail.itemCode.itemName}}</li>
            <li>   商品编码: {{order_detail.itemCode.itemCode}}</li>
            <li>   商品链接: {{order_detail.itemCode.itemLink}}</li>
            <li>      备注: {{order_detail.itemCode.remark}}</li>
            <li>       要求: {{order_detail.itemCode.requirements}}</li>
        </ul>
    </div>

    <!-- 订单详细信息 时间、关键字、入口、浏览时间、是否假聊、购买件数、单数、价格、佣金、留言、刷手费用、
        是否完成、是否返款、异常、备注、淘宝用户名 -->
<!--
    <div>
        <h2>订单详细信息</h2>
        <form action="" method="post">
        <ul>
            <li>时间: <input type="date" name="dateTime" value="{{order_detail.dateTime}}"></li>
            <li>关键字: <input style="width:30%" type="text" name="keywords" value="{{order_detail.keywords}}"></li>
            <li>入口: <input type="text" name="enterChannel" value="{{order_detail.enterChannel}}"></li>
            <li>浏览时长: <input type="number" name="scanDuration" value="{{order_detail.scanDuration}}"> 分钟</li>
            <li>是否假聊:
                <select name="talk" value="{{order_detail.get_talk_display}}">
                    <option value="0">否</option>
                    <option value="1">是</option>
                </select></li>
            <li>购买件数: <input type="number" name="shoppingCnt" value="{{order_detail.shoppingCnt}}"></li>
            <li>单数: <input type="number" name="orderCnt" value="{{order_detail.orderCnt}}"></li>
            <li>价格: <input type="number" name="price" value="{{order_detail.price}}"></li>
            <li>佣金: <input type="number" name="charges" value="{{order_detail.charges}}"></li>
            <li>留言: <textarea name="memo">{{order_detail.memo}}</textarea></li>
            <li>刷手费用: <input type="number" name="salary" value="{{order_detail.salary}}"></li>
            <li>是否完成:
                <select name="finishStatus" value="{{order_detail.get_finishStatus_display}}">
                    <option value="-1">异常</option>
                    <option value="0">未完成</option>
                    <option value="1">已完成</option>
                </select></li>
            <li>是否返款:
                <select name="moneyReturnStatus"  value="{{order_detail.get_moneyReturnStatus_display}}">
                    <option value="-1">异常</option>
                    <option value="0">未返款</option>
                    <option value="1">已返款</option>
                </select></li>
            <li>异常: <textarea name="exception" >{{order_detail.exception}}</textarea></li>
            <li>备注: <textarea name="remark">{{order_detail.remark}}</textarea></li>
            <li>淘宝用户名: <input type="text" name="userTaobaoId" value="{{order_detail.userTaobaoId}}"></li>
        </ul>
            <input style="margin-right:100px;" type="submit">
        </form>
    </div>
-->

    <!-- 订单详细信息 时间、关键字、入口、浏览时间、是否假聊、购买件数、单数、价格、佣金、留言、刷手费用、
        是否完成、是否返款、异常、备注、淘宝用户名 -->
    <div>
        <h2>订单详细信息</h2>
        <form action="{% url 'ordering_info:modify info' order_detail.id %}" method="post">
        {% csrf_token %}
        <table>
            <tr>
                <th><label for="id_dateTime">时间:</label></th>
                <td><input style="padding-left:5px;" type="date" name="dateTime" required id="id_dateTime" value="{{order_detail.dateTime | date:'Y-n-d'}}"></td>
            </tr>
            <tr>
                <th><label for="id_keywords">关键字:</label></th>
                <td><input style="padding-left:5px;" type="text" name="keywords" required maxlength="64" id="id_keywords" value="{{order_detail.keywords}}"></td>
            </tr>
            <tr>
                <th><label for="id_enterChannel">入口:</label></th>
                <td>
                    <input style="padding-left:5px;" type="text" name="enterChannel" required maxlength="24" id="id_enterChannel" value="{{order_detail.enterChannel}}">
                </td>
            </tr>
            <tr>
                <th><label for="id_scanDuration">浏览时间:</label></th>
                <td>
                    <input style="padding-left:5px;" type="number" name="scanDuration" required id="id_scanDuration" value="{{order_detail.scanDuration}}"> 分钟
                </td>
            </tr>
            <tr>
                <th><label for="id_talk">是否假聊:</label></th>
                <td>
                    <select name="talk" required id="id_talk">
                        <option value="0" {% if order_detail.talk == 0 %} selected {% endif %}>否</option>
                        <option value="1" {% if order_detail.talk %} selected {% endif %}>是</option>
                    </select>
                </td>
            </tr>
            <tr>
                <th><label for="id_shoppingCnt">购买件数:</label></th>
                <td>
                    <input style="padding-left:5px;" type="number" name="shoppingCnt" required id="id_shoppingCnt" value="{{order_detail.shoppingCnt}}">
                </td>
            </tr>
            <tr><th><label for="id_orderCnt">单数:</label></th>
                <td>
                    <input style="padding-left:5px;" type="number" name="orderCnt" required id="id_orderCnt" value="{{order_detail.orderCnt}}">
                </td>
            </tr>
            <tr>
                <th><label for="id_price">价格:</label></th>
                <td>
                    <input style="padding-left:5px;" type="number" name="price" step="any" required id="id_price" value="{{order_detail.price}}"> 元
                </td>
            </tr>
            <tr>
                <th><label for="id_charges">佣金:</label></th>
                <td>
                    <input style="padding-left:5px;" type="number" name="charges" step="any" required id="id_charges" value="{{order_detail.charges}}"> 元
                </td>
            </tr>
            <tr>
                <th><label for="id_memo">留言:</label></th>
                <td>
                    <textarea style="padding-left:3px;" name="memo" id="id_memo" required cols="40" rows="10" >{{order_detail.memo}}</textarea>
                </td>
            </tr>
            <tr>
                <th><label for="id_salary">刷手费用:</label></th>
                <td>
                    <input style="padding-left:5px;" type="number" name="salary" step="any" required id="id_salary" value="{{order_detail.salary}}"> 元
                </td>
            </tr>
            <tr>
                <th><label for="id_finishStatus">是否完成:</label></th>
                <td>
                    <select name="finishStatus" required id="id_finishStatus" value="{{order_detail.finishStatus}}">
                        <option value="-1" {% if order_detail.finishStatus == -1 %} selected {% endif %}>异常</option>
                        <option value="0" {% if order_detail.finishStatus == 0 %} selected {% endif %}>未完成</option>
                        <option value="1" {% if order_detail.finishStatus == 1 %} selected {% endif %}>已完成</option>
                    </select>
                </td>
            </tr>
            <tr>
                <th><label for="id_moneyReturnStatus">是否返款:</label></th>
                <td>
                    <select name="moneyReturnStatus" required id="id_moneyReturnStatus">
                        <option value="-1" {%if order_detail.moneyReturnStatus == -1 %} selected {% endif %}>异常</option>
                        <option value="0" {%if order_detail.moneyReturnStatus == 0 %} selected {% endif %}>未返款</option>
                        <option value="1" {%if order_detail.moneyReturnStatus == 1 %} selected {% endif %}>已返款</option>
                    </select>
                </td>
            </tr>
            <tr>
                <th><label for="id_exception">订单是否出错:</label></th>
                <td>
                    <select name="exception" required id="id_exception">
                        <option value="0" {%if order_detail.exception == 0 %} selected {% endif %}>错误</option>
                        <option value="1" {%if order_detail.exception %} selected {% endif %}>正确</option>
                    </select>
                </td>
            </tr>
            <tr>
                <th><label for="id_remark">备注:</label></th>
                <td>
                    <textarea style="padding-left:3px;"name="remark" id="id_remark" required cols="40" rows="10">{{order_detail.remark}}</textarea>
                </td>
            </tr>
            <tr>
                <th><label for="id_userTaobaoId">淘宝用户名:</label></th>
                <td>
                    <input style="padding-left:5px;" type="text" name="userTaobaoId" required maxlength="64" id="id_userTaobaoId" value="{{order_detail.userTaobaoId.userTaobaoId}}">
                </td>
            </tr>
        </table><br>
            <button style="padding-left:20px;padding-right:20px;" type="submit">更新</button>
    </form>
    </div>
</head>
<body>

</body>
</html>

ordering_manage/ordering_info/templates/ordering_info/orderinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>订单列表</title>
    <table border="1" cellspacing="0" style="border:none;line-height:29px;height:29px;border-radius:1px;width:100%;">
        <tr>
            <!-- 时间、店铺名称、商品名称、购买件数、价格、淘宝用户名、是否完成、是否返款、异常、操作 -->
            <td align="center">时间</td>
            <td align="center">店铺名称</td>
            <td align="center">商品名称</td>
            <td align="center">购买件数</td>
            <td align="center">价格</td>
            <td align="center">淘宝用户名</td>
            <td align="center">是否完成</td>
            <td align="center">是否返款</td>
            <td align="center">订单是否出错</td>
            <td align="center">操作</td>
        </tr>
        {% for order_post in order_posts %}
        <tr>
            <td align="center">{{order_post.dateTime | date:'Y-n-d'}}</td>
            <td align="center">{{order_post.itemCode.shopId.shopName}}</td>
            <td align="center">{{order_post.itemCode.itemName}}</td>
            <td align="center">{{order_post.orderCnt}}</td>
            <td align="center">{{order_post.price }} 元</td>
            <td align="center">{{order_post.userTaobaoId}}</td>
            <td align="center">{{order_post.get_finishStatus_display}}</td>
            <td align="center">{{order_post.get_moneyReturnStatus_display}}</td>
            <td align="center">{{order_post.get_exception_display}}</td>
            <td align="center">
                <!-- 详细信息、删除、修改 -->
                <button type="submit" name="detail" class="btn btn-orderinfo">
                    <a href="{% url 'ordering_info:show detail' order_post.id %}" style="text-decoration:none;">详细信息</a>
                </button>
                <button type="submit" name="delete" class="btn btn-orderinfo">
                    <a href="{% url 'ordering_info:delete order' order_post.id %}" style="text-decoration:none;">删除</a>
                </button>
            </td>
        </tr>
        {% endfor %}
    </table>
</head>
<body>

</body>
</html>

ordering_manage/ordering_info/templates/ordering_info/search-base.html
<header id="site-header">
    <div id="header-search-box">
        <form role="search" method="get" id="searchform" action="{% url 'ordering_info:search orders' %}">
            {% csrf_token %}
            <th><label id="id_datetime">时间:</label></th>
            <input type="date" name="datetime" value="">

            <th><label id="id_keywords" style="padding-left:20px">关键字:</label></th>
            <input type="text" name="keywords">

            <th><label for="id_finishStatus" style="padding-left:20px">是否完成:</label></th>
            <select name="finishStatus" required id="id_finishStatus" value="{{order_detail.finishStatus}}">
                <option value="-1">异常</option>
                <option value="0">未完成</option>
                <option value="1" selected>已完成</option>
            </select>

            <th><label for="id_moneyReturnStatus" style="padding-left:20px">是否返款:</label></th>
            <select name="moneyReturnStatus" required id="id_moneyReturnStatus">
                <option value="-1">异常</option>
                <option value="0">未返款</option>
                <option value="1" selected>已返款</option>
            </select>

            <th><label for="id_userTaobaoId" style="padding-left:20px">淘宝用户名:</label></th>
            <input type="text" name="userTaobaoId">

            <button type="submit">搜索</button>
        </form>
    </div>
</header>